name: otona_book_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  flutter_staggered_grid_view: ^0.7.0
  json_serializable: ^6.7.1
  cached_network_image: ^3.2.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true
